name             'glusterfs'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures glusterfs'
long_description 'Installs/Configures glusterfs'
version          '0.1.0'
depends          'dbag'
